# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('students', '0003_auto_20161018_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcoursemapping',
            name='options',
            field=models.ManyToManyField(to='questions.Option'),
        ),
    ]
