# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20161023_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorcoursemapping',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='professorcoursemapping',
            name='professor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor_courses', to='students.SiteUser'),
        ),
    ]
