# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_year'),
        ('students', '0007_auto_20161027_1801'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='professorcoursemapping',
            unique_together=set([('professor', 'course')]),
        ),
    ]
