# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20161027_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorcoursemapping',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_courses', to='students.SiteUser'),
        ),
    ]
