# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20161027_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorcoursemapping',
            name='questions',
            field=models.ManyToManyField(null=True, to='questions.Question'),
        ),
        migrations.AlterField(
            model_name='studentcoursemapping',
            name='options',
            field=models.ManyToManyField(null=True, to='questions.Option'),
        ),
    ]
