# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20161027_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcoursemapping',
            name='all_questions_answered',
            field=models.BooleanField(default=False),
        ),
    ]
