# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_studentcoursemapping_all_questions_answered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcoursemapping',
            name='all_questions_answered',
        ),
    ]
