# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20161101_2357'),
        ('students', '0013_remove_studentcoursemapping_all_questions_answered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.ManyToManyField(null=True, to='questions.Question')),
            ],
        ),
        migrations.RemoveField(
            model_name='professorcoursemapping',
            name='questions',
        ),
        migrations.AddField(
            model_name='professorcoursemapping',
            name='config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Config'),
        ),
    ]
