# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20161110_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='questions',
            field=models.ManyToManyField(to='questions.Question'),
        ),
        migrations.AlterField(
            model_name='studentcoursemapping',
            name='options',
            field=models.ManyToManyField(to='questions.Option'),
        ),
    ]
