# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_auto_20161110_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='questions',
        ),
        migrations.AlterField(
            model_name='professorcoursemapping',
            name='config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Config'),
        ),
        migrations.DeleteModel(
            name='Config',
        ),
    ]
