# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_auto_20161124_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcoursemapping',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_mappings', to='courses.Course'),
        ),
    ]
