# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_auto_20161124_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcoursemapping',
            name='group',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
