# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
