# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20161027_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option',
            field=models.TextField(default=''),
        ),
    ]
