# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20161111_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='config',
        ),
        migrations.AddField(
            model_name='config',
            name='questions',
            field=models.ManyToManyField(to='questions.Question'),
        ),
    ]
